import { lazy } from "react";

export const AdminOverviewPanel = lazy(() => import("../../components/invest/AdminOverviewPanel.jsx"));
export const LedgerTable = lazy(() => import("../../components/invest/LedgerTable.jsx"));
export const DepositPaymentAccountsPanel = lazy(() => import("../../components/invest/DepositPaymentAccountsPanel.jsx"));
export const InvestSettingsPanel = lazy(() => import("../../components/invest/InvestSettingsPanel.jsx"));
export const CommunicationSettingsPanel = lazy(() => import("../../components/invest/CommunicationSettingsPanel.jsx"));
export const TodayPendingPayments = lazy(() => import("../../components/invest/MaturityPaymentsAdmin.jsx").then((m) => ({ default: m.TodayPendingPayments })));
export const UpcomingPayments = lazy(() => import("../../components/invest/MaturityPaymentsAdmin.jsx").then((m) => ({ default: m.UpcomingPayments })));
export const AdminAgreementsPanel = lazy(() => import("../../components/invest/AgreementsPanel.jsx").then((m) => ({ default: m.AdminAgreementsPanel })));
export const PromoCodesAdmin = lazy(() => import("../../components/invest/AdminExtrasPanels.jsx").then((m) => ({ default: m.PromoCodesAdmin })));
export const AuditLogPanel = lazy(() => import("../../components/invest/AdminExtrasPanels.jsx").then((m) => ({ default: m.AuditLogPanel })));
export const PartnersCmsPanel = lazy(() => import("../../components/invest/AdminExtrasPanels.jsx").then((m) => ({ default: m.PartnersCmsPanel })));
export const BroadcastNotificationsPanel = lazy(() => import("../../components/invest/AdminExtrasPanels.jsx").then((m) => ({ default: m.BroadcastNotificationsPanel })));
export const SupportTicketsAdmin = lazy(() => import("../../components/invest/AdminExtrasPanels.jsx").then((m) => ({ default: m.SupportTicketsAdmin })));
export const ReferralEarningsAdmin = lazy(() => import("../../components/invest/ReferralAdminPanel.jsx").then((m) => ({ default: m.ReferralAdminPanel })));
export const AccountSecurityPanel = lazy(() => import("../../components/shared/AccountSecurityPanel.jsx"));
export const TreasuryPanel = lazy(() => import("../../components/invest/AdminAdvancedPanels.jsx").then((m) => ({ default: m.TreasuryPanel })));
export const CohortAnalyticsPanel = lazy(() => import("../../components/invest/AdminAdvancedPanels.jsx").then((m) => ({ default: m.CohortAnalyticsPanel })));
export const RbacPanel = lazy(() => import("../../components/invest/AdminAdvancedPanels.jsx").then((m) => ({ default: m.RbacPanel })));
export const SupportMailPanel = lazy(() => import("../../components/invest/AdminAdvancedPanels.jsx").then((m) => ({ default: m.SupportMailPanel })));
export const PlatformInvestmentsPanel = lazy(() => import("../../components/invest/PlatformInvestmentsPanel.jsx"));
export const UsersManagementPanel = lazy(() => import("../../components/invest/InvestorOpsPanel.jsx"));
export const WalletOperationsPanel = lazy(() => import("../../components/invest/AdminOpsPanels.jsx").then((m) => ({ default: m.WalletOperationsPanel })));
export const HomepageCmsPanel = lazy(() => import("../../components/invest/AdminOpsPanels.jsx").then((m) => ({ default: m.HomepageCmsPanel })));
export const NotificationManagementPanel = lazy(() => import("../../components/invest/AdminOpsPanels.jsx").then((m) => ({ default: m.NotificationManagementPanel })));
export const BackupExportPanel = lazy(() => import("../../components/invest/AdminOpsPanels.jsx").then((m) => ({ default: m.BackupExportPanel })));
export const PayoutsAdmin = lazy(() => import("../../components/invest/AdminPayoutsPanel.jsx"));
export const PlansAdmin = lazy(() => import("../../components/invest/AdminPlansPanel.jsx"));
export const DepositsAdmin = lazy(() => import("../../components/invest/AdminDepositsPanel.jsx"));
export const KycAdmin = lazy(() => import("../../components/invest/AdminKycPanel.jsx"));
export const StaffAdmin = lazy(() => import("../../components/invest/AdminStaffPanel.jsx"));
